# Generated by Django 3.2.5 on 2021-10-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_userprofile_courses'),
        ('course', '0002_rename_course_model_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='fixme', max_length=75),
            preserve_default=False,
        ),
    ]
