# Generated by Django 3.2.5 on 2021-11-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_userprofile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='Your name', max_length=255),
        ),
    ]
