# Generated by Django 3.2.5 on 2021-11-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20211028_0304'),
        ('Profile', '0005_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='course.Course'),
        ),
    ]
